modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "CC0"

[[mods]]
modId = "alchimiae"
version = "${version}"
displayName = "Alchimiae Magicae"
authors = "SSBlur"
description = '''
Brews, potions, all sorts of concoctions. All at the tip of your pestle!
'''
logoFile = "assets/alchimiae/icon.png"

[[dependencies.alchimiae]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.alchimiae]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.alchimiae]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "alchimiae.mixins.json"
